#include EASTL_ARENA_ALLOCATOR_HEADER

#ifndef EA_PRAGMA_ONCE_SUPPORTED
#define EA_PRAGMA_ONCE_SUPPORTED
#endif

#ifndef EASTL_SIZE_T_32BIT
#define EASTL_SIZE_T_32BIT 1
#endif

#ifndef EASTL_CUSTOM_FLOAT_CONSTANTS_REQUIRED
#define EASTL_CUSTOM_FLOAT_CONSTANTS_REQUIRED 1
#endif

#ifndef EA_HAVE_CPP11_INITIALIZER_LIST
#define EA_HAVE_CPP11_INITIALIZER_LIST 1
#endif

