#pragma once

#ifdef CYPRESS_GW1
#define CYPRESS_GW_SELECT(GW1, GW2, BFN) GW1
#elif CYPRESS_GW2
#define CYPRESS_GW_SELECT(GW1, GW2, BFN) GW2
#elif CYPRESS_BFN
#define CYPRESS_GW_SELECT(GW1, GW2, BFN) BFN
#endif

#ifdef _DEBUG
#define HAS_DEDICATED_SERVER TRUE
#define HAS_INGAME_CONSOLE TRUE
#define CAN_HOST_SERVER TRUE
#else
#define HAS_DEDICATED_SERVER TRUE
#define HAS_INGAME_CONSOLE TRUE
#define CAN_HOST_SERVER TRUE
#endif